name: linux-x64

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        framework: [ 'net9.0' ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '9.0.x'
    - name: Unit tests
      run: dotnet test test/unit/SIPSorcery.UnitTests.csproj --framework  ${{ matrix.framework }} -c Release
